version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - '3010:3010'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - '3333:3333'

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: fffk10
      MYSQL_PASSWORD: test
    volumes:
      - ./db/data:/var/lib/mysql
